name: EPointsSC
main: me.chr1s0143.EPointsSC.epoints
version: 1.0
author: Chris Hall
description: Simple plugin for non-ops to credit winners of games in spleef/parkour etc with enjin points

commands:
  epoints:
    usage: /epoints
    description: /epoints (player name) - Credit the player with points set in the config.yml (Default 2)
    aliases: [ep,eps]
  epreload:
    usage: /epreload
    description: reload the config
    aliases: [epr]

permissions:
    epoints.use:
        description: Access to /epoints (name)